"""Generate ``src/ducktype/analysis/idiom_data.py`` from a raw idiom corpus.

The dashboard's 成语 panel used to flag *every* 4-character all-Han word as an
idiom -- wildly over-counting (most 4-char jieba words are ordinary
collocations, names, 关注词…). Instead we ship a real idiom dictionary and test
membership against it.

Source corpus: the public 中华新华字典数据库 (pwxcoo/chinese-xinhua) ``idiom.json``
(~30k idioms). Download once, then run this script:

    curl -L -o _idiom_raw.json \
      https://raw.githubusercontent.com/pwxcoo/chinese-xinhua/master/data/idiom.json
    python tools/build_idioms.py _idiom_raw.json

Punctuation is stripped from every entry, so multi-clause idioms written with a
comma in the dictionary (e.g. ``胜不骄，败不馁``) become the contiguous Han run a
user actually types (``胜不骄败不馁``) -- the committed-character stream never
contains the comma. The output groups idioms by length so the runtime scanner
only has to slide windows of the lengths that actually occur.
"""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

HAN = lambda c: "一" <= c <= "鿿" or "㐀" <= c <= "䶿"
OUT = Path(__file__).resolve().parent.parent / "src" / "ducktype" / "analysis" / "idiom_data.py"


def main(src: str) -> None:
    data = json.load(open(src, encoding="utf-8"))
    by_len: dict[int, set] = collections.defaultdict(set)
    for entry in data:
        word = "".join(c for c in entry.get("word", "") if HAN(c))
        # 2-char "idioms" overlap far too much with ordinary words to flag
        # safely; idioms worth surfacing are 3+ characters.
        if len(word) >= 3:
            by_len[len(word)].add(word)

    four = "".join(sorted(by_len.pop(4, ())))           # all exactly 4 chars
    other = sorted((w for s in by_len.values() for w in s), key=lambda w: (len(w), w))

    lines = [
        '"""Idiom dictionary for 成语 detection -- generated by tools/build_idioms.py.',
        "",
        "Do not edit by hand. ``_FOUR`` is every 4-character idiom concatenated (split",
        "back out in 4-char slices); ``_OTHER`` holds the less common non-4-char idioms.",
        '"""',
        "",
        f"# {len(four)//4} four-character idioms",
        "_FOUR = (",
    ]
    # Chunk the big 4-char string so no single source line is absurdly long.
    for i in range(0, len(four), 1600):
        lines.append("    " + repr(four[i:i + 1600]))
    lines.append(")")
    lines.append("")
    lines.append(f"# {len(other)} idioms of other lengths (3, 5-14 chars)")
    lines.append("_OTHER = (")
    for i in range(0, len(other), 8):
        lines.append("    " + " ".join(repr(w) + "," for w in other[i:i + 8]))
    lines.append(")")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} : {len(four)//4} four-char + {len(other)} other idioms")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "_idiom_raw.json")
